[app]

name = "远程通"
short_name = "远程通"
company = "远程通"

[rendezvous]

server = "yc.niani.top"
key = "YOoTNd4Ff5SA3mvHPWoCUjG99tZfHN82SWMZRQQNqsQ="

[ui]

logo = "res/logo256.png"
icon = "res/icon256.ico"

[update]

disable = true
