name: Build RustDesk Custom

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build
      run: |
        cargo build --release

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: 远程助手
        path: target/release/*.exe
